//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftITMvc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Projects = new HashSet<Project>();
        }
    
        public int EmployeeId { get; set; }
        [Display(Name = "Név")]
        public string FullName { get; set; }
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        public string Skype { get; set; }
        [DataType(DataType.PhoneNumber)]
        public string Tel { get; set; }
    
        public virtual ICollection<Project> Projects { get; set; }
    }
}
