//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftITMvc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Project
    {
        public Project()
        {
            this.Workflows = new HashSet<Workflow>();
        }
    
        public int ProjectId { get; set; }
        [Display(Name = "Név")]
        public string Name { get; set; }
        [Display(Name = "Leírás")]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }
        public string Logo { get; set; }
        [Display(Name = "Megrendelő")]
        public string ProcurerId { get; set; }
        [Display(Name = "Méret")]
        public LogoSize Size { get; set; }
        [Display(Name = "Állapot")]
        public ProjectState State { get; set; }
        [Display(Name = "Határidő")]
        [DataType(DataType.Date)]
        public string Deadline { get; set; }
        public int EmployeeId { get; set; }
        [Display(Name = "Ár")]
        [DataType(DataType.Currency)]
        public int Price { get; set; }
        [Display(Name = "Értékelés")]
        [DataType(DataType.MultilineText)]
        public string Rating { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ICollection<Workflow> Workflows { get; set; }
    }
}
