//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftITMvc.Models
{
    using System;
    
    public enum ProjectState : int
    {
        Ongoing = 0,
        Waiting = 1,
        Ready = 2
    }
}
