//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftITMvc.Models
{
    using System;
    
    public enum ProjectState : int
    {
        WaitingForApproval = 0,
        WaitingForBet = 1,
        InProggress = 2,
        Beta = 3,
        Ready = 4,
        Terminated = 5,
        Finished = 6
    }
}
